### ISSUE TITLE
mass not sent to all artists

### ISSUE THREAD

**Issue by rubendegroote** [rubendegroote/Networked-Data-Acquisition#10]

**Comment by woutergins** [comment]
Added method similar to **set_all_scan_numbers** to Controller.py, and a corresponding method **set_mass** in Device.py. **set_all_masses** is called right after **set_all_scan_numbers**, and given the similarity, it should work. Needs to be tested.

**Comment by rubendegroote** [comment]
Does not seem to be fixed. Will investigate

**Comment by woutergins** [comment]
Did the setting of the scan numbers work previously? I can't see any difference in logic between the methods...

**Comment by rubendegroote** [comment]
It sure does.

**Comment by rubendegroote** [comment]
Fixed.
