### ISSUE TITLE
Manager scanner info

### ISSUE THREAD

**Issue by rubendegroote** [rubendegroote/Networked-Data-Acquisition#11]
Manager does not know which artist is scanning if it is restarted. As a consequence, the scan cannot be stopped...

**Comment by rubendegroote** [comment]
This info can probably be added to the ini file that saves the last scan number.

**Comment by woutergins** [comment]
Added progress tracking to .ini file. Again, code is untested.

**Comment by rubendegroote** [comment]
Will test code now!

**Comment by rubendegroote** [comment]
Had a small bug, is fixed now.
