### ISSUE TITLE
Setpoint reached status indicator in Controler app

### ISSUE THREAD

**Issue by rubendegroote** [rubendegroote/Networked-Data-Acquisition#13]

**Comment by woutergins** [comment]
Added rudimentary indicator for the boolean **on_setpoint**. Current assumption is that this is passed in the _status_data_ dictionary from the device.
The text **Yes** is displayed if the boolean is true, **No** if it is false. This could in the future be updated to a green/red button.

**Comment by rubendegroote** [comment]
Your assumption is correct.
