### ISSUE TITLE
Radio conversion

### ISSUE THREAD

**Issue by woutergins** [rubendegroote/Networked-Data-Acquisition#3]
The Radio is almost ready, small changes still need to be made to have it working as intended.

**Comment by rubendegroote** [comment]
Radio is expanded in scope to be a viewer of the live data (stream or current scan) but also of old data. For this it has to connect to the file server. The old scans are grouped per mass.
The logbook viewer no longer connects to the file server.

**Comment by rubendegroote** [comment]
Radio - data server communications are done.
Next is the communications with the fileserver. This server will access the hdf5 file on disk and slice as needed.

**Comment by rubendegroote** [comment]
File server communications done.

Next: fix bug in plotting: jittery plots. Probably the backfill-front fill stuff.

**Comment by rubendegroote** [comment]
Done.
