### ISSUE TITLE
Isotope saving

### ISSUE THREAD

**Issue by woutergins** [rubendegroote/Networked-Data-Acquisition#4]
Each scan should specify which isotope it contains. Since the format is already saved as an attribute/hashmap, maybe save the isotope the same way?

**Comment by rubendegroote** [comment]
Some brainstorming on this.

When starting a scan, an isotope number is asked. This gets sent to the manager along with the usual scan properties. The Artist adds this to a dict with scan numbers as keys and masses as the values. This dict is indeed saved as an attribute in the datafile.
The isotope dict is also sent to the dataserver so it can add it to the aggregated data files. 
The manager also puts the mass in the logbook, so it gets added to all viewers.

**Comment by rubendegroote** [comment]
Done.
