### ISSUE TITLE
Hardware integration

### ISSUE THREAD

**Issue by woutergins** [rubendegroote/Networked-Data-Acquisition#6]
Integrate the M2 laser into the system, such that the lock status and controls can also be seen in the Manager GUI.

**Comment by rubendegroote** [comment]
Extra work: PID loop for systems that need stabilizing.

**Comment by rubendegroote** [comment]
Matisse works.

**Comment by rubendegroote** [comment]
Controlling the M2 mostly works.

To be added: the artist should not start working until it has received the current wavelength and the current cavity tuning percentage - so it knows where to start the PID. So, the manager gui and manager need to be changed slightly, and the acquisition should start halted.

**Comment by rubendegroote** [comment]
Just added an initialization option. If specified, artist waits for an initialization before proceeding with the daq loop.

Also needed: a pauze acquisition button/option.

**Comment by rubendegroote** [comment]
M2 laser done!

Next up: NI DAQ cards.

**Comment by rubendegroote** [comment]
NI cards work.
