### ISSUE TITLE
Suppress error dialog pop ups if there is a recurring error

### ISSUE THREAD

**Issue by rubendegroote** [rubendegroote/Networked-Data-Acquisition#8]
Often when something goes wrong, the same error is thrown all the time. There should a suppression of similar errors within a certain time span or something.

**Comment by woutergins** [comment]
Currently fixed (hopefully) by keeping a dictionary of error messages, and a timestamp. If the timestamp is older than 5s, or the key is not in the dictionary, an error message is displayed. Quick fix, this definitely needs more work (cleaning the dictionary, for example).

**Comment by rubendegroote** [comment]
I think this is fine as it is. There is a limited number of possible error messages, so I don't think the dict needs to be cleaned.
